version: "3"

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
#includes:
#  rs:
#    taskfile: ./iDev/coding/rs/
#    dir: ./iDev/coding/rs/

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  default:
    cmds:
      - task: install
      - task: run

  init:
    cmds:
      - cp .env.local .env

  install:
    cmds:
      - cd packages/axum/axum-axum-v0.4.5/; cargo update

  run:hello:
    cmds:
      - cd packages/axum/axum-axum-v0.4.5/examples/hello-world/; cargo run


  push:
    cmds:
      - git push origin main --tags

  ############################################################################




